baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "Fernandez B"
  description: My profile
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo1.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Fernandez. " # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Brandon Fernandez."
    subtitle: "Computer Science Student"
    content: "As an aspiring Software Developer I am passionate for using new techonologies and creating new things using my programming skills. "
    image: /headshot.jpg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/Resume 2023-2024 v3.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Athem123
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/brandon-fernandez-624191255/
        - icon: fab fa-instagram
          url: https://www.instagram.com/brandon_fernandez02/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/headshot.jpg"
    roundimage: true
    content: |-
      I am a second year Computer Science Co-op student at Brock University in St. Catharines, ON. Ever since I was young, I have had great interest in computers and new technologies, which inspired me to learn programming. 
      
      I am currently working part-time at the Meridian Centre in St. Catharines, however I am also searching for a Summer 2023 Software Engineer Co-op placement.
  
    skills: 
          enable: true
          title: "Here are a few technologies I've been working with recently:"
          items:
            - "Java"
            - "Python"
            - "C++"
            - "HTML"
            - "SQL"
            - "MIPS"
            - "Linux Command Line"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Parking Lot Supervisor and General Worker"
        company: "Meridian Centre"
        companyUrl: "https://www.meridiancentre.com"
        date: "Octuber 2022 - present"
        content: "I am currently working part-time at the Meridian Centre in St Catharines. I am in charge of the parking lot and making sure VIPs have the necessary accomodations. Due to the nature of the job I talk to hundreds of customers every shift which has greatly improved my communication skills."

      - job: "Warehouse Associate - Order Picker"
        company: "Metrie"
        companyUrl: "https://www.metrie.com"
        date: "Sep 2020 - Dec 2021"
        info:
          enable: true
          content: I worked as a warehouse associate for almost one year in Metrie.
        content: |
          Picked 10+ customer orders daily in a timely manner, resulting in increased productivity.
          Decreased customer returns by properly picking and assembling customer orders.
          Reduced workplace accidents by reporting and fixing warehouse hazards.
          Improved department efficiency by taking initiative and communicating about issues with materials and orders.

      - job: "Volunteer"
        company: "RBC Canadian Open"
        date: "July 2017 and July 2018"
        content: |
          Increased department efficiency by participating in both the security and customer service departments.
          Worked with 2 teams of over 20 members. Actively communicated with my co-workers through in-person 
          meetings, email updates, to ensure that everyone was working effectively towards our shared goals. 

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Honours Bachelor of Science in Computer Science Co-op. Minor in Mathematics"
        school:
          name: "Brock University | St. Catharines, ON."
        date: "2022 - Present"
        GPA: "4.0 out of 4.0"
        content: |-
          Course work:
          - Advanced use of Python, Java, C++. Intermediate use of Assembly and SQL.
          - program testing, error handling, and fault-tolerance integration, data structures, Object-Oriented 
            Programming, algorithms. Currently learning database design and application.
          Technologies used:
          - IntelliJ, Visual Studio Code and Linux command line.
          - Excel, Word, Powerpoint.

      - title: "Computer Science, Mathematics and Statistics"
        school:
          name: "University of Toronto Mississauga | Mississauga, ON"
        date: "2021 - 2022"
        GPA: "3.5 out of 4.0"
        content: |-
          Course work:
          - Advanced use of Python.
          - program testing, error handling, data structures, Object-Oriented 
            Programming.
          Technologies used:
          - PyCharm, Visual Studio Code
      - title: "High School Diploma"
        school:
          name: "St. Francis Xavier Catholic Secondary school | Milton, ON"
        GPA: "91 out of 100"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: University of Toronto Mississauga | International Scholar Award
        content: Automatically awarded to exceptional international students at the University of Toronto Mississauga. Recipients are selected by committee. Based on academic achievement and overall academic competitiveness.
      - title: Ontario Ministry of Education | Ontario Scholar Award
        content: High School graduates with an average of 80% or more on best grade 12 courses
      - title: Saint Francis Xavier Catholic Secondary School | Computer Engineering Academic Award
        content: Awarded to the student with the highest grade of the school in the grade 11 Computer Engineering class.
      - title: Saint Francis Xavier Catholic Secondary School | Honour Roll 2017 - 2019
        content: Awarded to students with an average of 85% or more in the corresponding grade.

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Text Encryption and Compression program
        content: Python program that takes in a text and using the frequency of the characters in the text, creates a binary search tree that is used with complex algorithms as well as the usage of bits from characters, encrypts the text. This program compresses any text because of the encryption algorithm I developed for this program. During testing, I used a thousand page book which was reduced by more than half its size and completely encrypted in less than 5 seconds.
        image: "/p5.jpg"
        badges:
          - "Python"
          - "Data Structures"
          - "Algorithms"

      - title: DrugBank Database Program
        content: Using a sample database of a drugbank, the program has multiple functionalities. Database is stored for the use of the program using matrices. Functions include, Search for a drug, find and connect/disconnect drugbank modules as well as their removal, sorting, etc.  
        image: "/drug_bank.jpg"
        badges:
          - "Java"
          - "Matrices"
          - "Heaps"
          - "Advanced Algorithms"

      - title: Videogame dabase
        image: "/database.jpg"
        content: School project where a database had to be designed according to the given parameters for a videogame. Created ER diagrams as well as schema in order to take the best possible approach
        badges:
          - "SQL"
          - "Database Design"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    email: bf22wk@brocku.ca
    btnName: bf22wk@brocku.ca
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"